[build]
builder = "DOCKERFILE"
dockerfilePath = "onboarding_backend/python/Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
