[build]
builder = "DOCKERFILE"
dockerfilePath = "onboarding_backend/python/Dockerfile"
contextPath = "onboarding_backend/python"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
