-- ============================================
-- Daily Surveys Schema for Bridge
-- ============================================
-- Daily grid assignments where a ranker votes on candidates for a recipient.
-- Column names from: surveyService.ts:37-47, developmentDataService.ts:327-335
-- FK constraint names must match surveyService.ts join aliases.

CREATE TABLE IF NOT EXISTS daily_surveys (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- The user doing the ranking/voting
    ranker_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

    -- The user being matched (the "anchor")
    recipient_user_id UUID NOT NULL
        CONSTRAINT daily_surveys_recipient_user_id_fkey
        REFERENCES auth.users(id) ON DELETE CASCADE,

    -- Three candidates to rank
    candidate_1_user_id UUID NOT NULL
        CONSTRAINT daily_surveys_candidate_1_user_id_fkey
        REFERENCES auth.users(id) ON DELETE CASCADE,

    candidate_2_user_id UUID NOT NULL
        CONSTRAINT daily_surveys_candidate_2_user_id_fkey
        REFERENCES auth.users(id) ON DELETE CASCADE,

    candidate_3_user_id UUID NOT NULL
        CONSTRAINT daily_surveys_candidate_3_user_id_fkey
        REFERENCES auth.users(id) ON DELETE CASCADE,

    -- Date of the survey
    survey_date DATE NOT NULL,

    -- Completion tracking
    is_completed BOOLEAN DEFAULT FALSE,
    completed_at TIMESTAMPTZ,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_daily_surveys_ranker ON daily_surveys(ranker_user_id);
CREATE INDEX IF NOT EXISTS idx_daily_surveys_date ON daily_surveys(survey_date);
CREATE INDEX IF NOT EXISTS idx_daily_surveys_ranker_date ON daily_surveys(ranker_user_id, survey_date);

-- ============================================
-- Row Level Security (RLS)
-- ============================================
ALTER TABLE daily_surveys ENABLE ROW LEVEL SECURITY;

-- Users can view surveys assigned to them
CREATE POLICY "Users can view their own surveys"
    ON daily_surveys FOR SELECT
    USING (auth.uid() = ranker_user_id);

-- Users can update their own surveys (mark complete)
CREATE POLICY "Users can update their own surveys"
    ON daily_surveys FOR UPDATE
    USING (auth.uid() = ranker_user_id)
    WITH CHECK (auth.uid() = ranker_user_id);

-- Insert via server/service role only (surveys are generated by backend)
CREATE POLICY "Service role can insert surveys"
    ON daily_surveys FOR INSERT
    WITH CHECK (TRUE);

-- Delete for cleanup
CREATE POLICY "Users can delete their own surveys"
    ON daily_surveys FOR DELETE
    USING (auth.uid() = ranker_user_id);
